### ISSUE TITLE
raise EOFError()

### ISSUE THREAD

**Issue by sxiaojian88** [fmzquant/backtest_python#4]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/sxiaojian/PycharmProjects/test/test.py", line 12, in <module>
    print exchange.GetTicker()
  File "/usr/local/lib/python2.7/site-packages/fmz.py", line 648, in GetTicker
    EOF()
  File "/usr/local/lib/python2.7/site-packages/fmz.py", line 569, in EOF
    raise EOFError()
EOFError

改成非LTC_BTC的交易对就会出现这个问题。
EOF就是回测没历史数据或者回测结束，那么，如何加载我需要的回测历史数据呢

**Comment by fyr233** [comment]
遇到了类似的问题。
复现代码：
```
>>> from fmz import *
>>> task = VCtx('backtest\nstart: 2021-10-20 00:00:00\nend: 2021-10-28 00:00:00\nperiod: 1m\nbasePeriod: 1m\nexchanges: [{"eid":"Futures_Binance","currency":"BTC_USDT","quotePrecision":3,"basePrecision":2,"fee":[0.02,0.04]}]\n')
>>> exchange.GetTicker()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\fmz.py", line 716, in GetTicker
    EOF()
  File "C:\Program Files\Python39\lib\site-packages\fmz.py", line 594, in EOF
    raise EOFError()
EOFError
```
